version: "3.3"
services:
  mongodb:
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - ./db:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: super
        MONGO_INITDB_ROOT_PASSWORD: sinan123
    networks:
        - skynet
    logging:
        driver: none
  react:
    image: react:1.0.0
    build:
      context: .
      dockerfile: dockerfiles/dockerfile
    # command: ["yarn", "start"]
    # command: ["yarn", "prod"]
    command: ["node", "index.js"]
    volumes:
      - ./react_docker:/usr/react_docker/
      - /usr/react_docker/node_modules
    ports:
      - "8080:8080"
    networks:
      - skynet
    depends_on:
      - mongodb
  nginx:
    image: nginx
    volumes:
    - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=sinan.com
    - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

networks:
  skynet:
